# Generated by Django 5.1.4 on 2025-02-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userprofile_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
