# Generated by Django 5.1.4 on 2025-02-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Course cover image', null=True, upload_to='course_images/'),
        ),
    ]
