# Generated by Django 5.1.4 on 2025-02-04 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_course_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, help_text='Upload lesson materials (PDF, DOC, etc.)', null=True, upload_to='lesson_files/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_created', to='myapp.teacher'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_published',
        ),
    ]
