# Generated by Django 5.1.4 on 2025-02-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_lessonresource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='lessonresource',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='file',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='url',
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='file',
            field=models.FileField(blank=True, help_text='Upload lesson materials (PDF, DOC, PPT, etc.)', null=True, upload_to='lesson_files/'),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='url',
            field=models.URLField(blank=True, help_text='URLs will be automatically extracted from the description', null=True),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('exam', 'Exam')], max_length=20)),
                ('link', models.URLField(help_text='Google Forms link')),
                ('max_score', models.PositiveIntegerField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='myapp.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='myapp.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='myapp.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assessment', 'student')},
            },
        ),
    ]
