# Generated by Django 5.1.4 on 2025-02-04 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_assessment_id_alter_assessmentscore_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='allow_submissions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='instructions_file',
            field=models.FileField(blank=True, null=True, upload_to='assessment_instructions/'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='submission_folder',
            field=models.CharField(blank=True, help_text='Google Drive folder ID for submissions', max_length=255),
        ),
        migrations.AddField(
            model_name='assessmentscore',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='link',
            field=models.URLField(blank=True, help_text='Google Forms link'),
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_file', models.FileField(upload_to='assessment_submissions/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('late', 'Late'), ('graded', 'Graded')], default='submitted', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='myapp.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to='myapp.student')),
            ],
            options={
                'ordering': ['-submission_date'],
                'unique_together': {('assessment', 'student')},
            },
        ),
    ]
